#!/bin/bash

function install {
    export NODE_TLS_REJECT_UNAUTHORIZED=0
    corepack enable
    yarn set version 4.5.1
    yarn config set nodeLinker node-modules
    yarn install
}

function start {
    npm run start 
}

$1 "${@:2}"